# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger: none
schedules:
- cron: "0 9 * * *"
  displayName: Every day at 9 am(utc) (오후 6시)
  branches:
    include:
    - main
  always: true


variables:
- group: Billing.RhipeCrawler.vg

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    export PYTHONPATH=$PYTHONPATH:$(System.DefaultWorkingDirectory)
    python main.py -t crawler
  displayName: 'crawler'
